products = [
    "Heritage",
    "Daconil Action",
    "Banner MAXX",
    "Headway",
    "Spectro",
    "Tartan",
    "Trinity",
    "Tourney",
    "Pillar",
    "Compass",
    "Segway",
    "Xzemplar",
    "Medallion",
    "Disarm",
    "Emerald",
    "3336",
    "Chipco",
    "Insignia",
    "Primo MAXX",
    "Trimmit",
    "Cutless",
    "Proxy",
    "Roundup",
    "Certainty",
    "Tenacity",
    "Dismiss",
    "Sedgehammer",
    "Image",
    "Drive XLR8"
]